// Generated by CoffeeScript 1.3.3
'use strict';

var TweetsCtrl,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

TweetsCtrl = function($scope, $http) {
  $scope.users = [];
  $scope.fetch = function() {
    return $http.jsonp('http://api.twitter.com/1/statuses/user_timeline.json?screen_name=' + $scope.current + '&callback=JSON_CALLBACK').success(function(data) {
      var _ref;
      $scope.tweets = data;
      if (_ref = $scope.current, __indexOf.call($scope.users, _ref) < 0) {
        return $scope.users.push($scope.current);
      }
    });
  };
  $scope.fetch_user = function(user) {
    $scope.current = user;
    return $scope.fetch();
  };
  return $scope.remove_user = function(user) {
    var newusers;
    newusers = $scope.users.filter(function(item) {
      return item !== user;
    });
    return $scope.users = newusers;
  };
};
